### PR TITLE
WIP: change cli backend to typer

### PR DESCRIPTION
**Pull request by abhijeetSaroha**
Change CLI backend to `typer`.

Solves #12

### CODE REVIEW

**Comment by abhijeetSaroha** [comment]
I have tries the file paths with `Path` but in backend, in some functions, it uses `endswith` method of str which is not compatible with `Path` type so, I don't change the type of file paths.

**Comment by abhijeetSaroha** [comment]
All commands works fine except text_to_speech, it gives error related to path. Most probably, error comes from backend. 

But with all other commands, they work seamlessly.
image

**Comment by xmnlab** [comment]
thanks for working on that @abhijeetSaroha !

in general looks good. some initial comments:

* rebase your branch on top of the upstream/main: https://github.com/osl-incubator/artbox/actions/runs/7589186134/job/20673466048?pr=18#step:3:13
* it looks like your code style is not correct, please run locally (in your conda environment): 
  * `pre-commit install`
  * `pre-commit run --all-files`

feel free to ping me if you have any questions! thanks

**Comment by abhijeetSaroha** [comment]
There are some uncommited changes like in `dev.yaml`, `poetry.lock` and `pyproject.toml` which we done to setup the artbox project in my system. Should I commit or stash those changes before rebase?

**Comment by xmnlab** [comment]
yep .. just run the rebase and fix that there.
in the rebase, for poetry.lock, you can just remove it manually and run again `poetry lock`

**Comment by abhijeetSaroha** [comment]
rebase don't run until I commit or stash those changes. So should I stash them ?

**Comment by xmnlab** [comment]
Hey @abhijeetSaroha,

Not sure if that would fix these conflict issues. But this is how I would do it:


* squash all your commits. You have 5 commits, so you should run the following command:

`git rebase -i HEAD~6`

Note: as we need to squash your 5 commits we need to rebase it on top of the 6th.

It should open an editor with all your 5 commits.

The first commit should be a pick (default), the all the other ones should be a flush.

Change each line with your 4 ladt commits. 

Save and exit. If everything worked ot will squash all your commits in your first commit.


If that worked, rebase your branch on top of the upstream/main:

`git rebase -i upstream/main`, you don't need to change anything, just save it an exit.

It will fail for that 2 files. It is Ok:

`rm poetry.lock` and `poetry lock`

For the change log, run `checkout upstream/main -- docs/changelog.md`

It will get the changelog.md from the upstream main.

Add your changes `git add -u`  and continue with the rebase `git rebase --continue`

Hope this will fix your issue there

**Comment by abhijeetSaroha** [comment]
Let me open an another pull request from scratch.

**Pull request closed without merging**
